GET https://bootcamp-api.codeit.kr/api/4-17/the-julge/users/88879132-0eb8-4c79-a43e-b18b06a06654/applications

Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4ODg3OTEzMi0wZWI4LTRjNzktYTQzZS1iMThiMDZhMDY2NTQiLCJpYXQiOjE3MTMzMzMwMjl9.N8OiyYmXVG81vwCiNhZHoHbJ8k2sTAh6J7toJhcwOGI"