POST https://bootcamp-api.codeit.kr/api/4-17/the-julge/shops
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyYjY0N2UwMy0wOWM4LTRhMzktOGU5Ni05MzBjZTNhODRhMjgiLCJpYXQiOjE3MTQxOTAxOTV9.MWkVrD2IafvjiS8HvSSW50nJeJDCoC3QlCU0KOV7QZ0

{
  "name": "test",
    "category": "양식",
    "address1": "서울시 종로구",
    "address2": "test",
    "description": "test",
    "imageUrl": "https://bootcamp-project-api.s3.ap-northeast-2.amazonaws.com/4-17/the-julge/d4c507f1-21e7-4e15-9d89-b8b656025a9b-sprint%20배너.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAQ32VNU3YNU4IZOFJ%2F20240426%2Fap-northeast-2%2Fs3%2Faws4_request&X-Amz-Date=20240426T132027Z&X-Amz-Expires=300&X-Amz-Signature=a73aac42c92a5d5839b90b3771d4e859b75b91cf481b8dfbe804ecf3825d5bb0&X-Amz-SignedHeaders=host&x-amz-acl=public-read&x-id=PutObject",
    "originalHourlyPay": "50000"
}

###
GET  https://bootcamp-api.codeit.kr/api/4-17/the-julge/users/ebe4f3e6-8d35-403c-8fbd-2842e25bde61

###
POST https://bootcamp-api.codeit.kr/api/4-17/the-julge/shops/ce2accc3-27ca-4742-b8f6-fd045869fa0c/notices
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyYjY0N2UwMy0wOWM4LTRhMzktOGU5Ni05MzBjZTNhODRhMjgiLCJpYXQiOjE3MTQxOTAxOTV9.MWkVrD2IafvjiS8HvSSW50nJeJDCoC3QlCU0KOV7QZ0

{
    "hourlyPay": "45000",
    "startsAt": "2024-11-23T00:00:00Z",
    "workhour": "6",
    "description": "test55"
}

###
GET https://bootcamp-project-api.s3.ap-northeast-2.amazonaws.com/4-17/the-julge/030f50c2-ad84-4db4-ba22-6697dad61cfe-sprint%20배너.png


###
GET https://bootcamp-api.codeit.kr/api/4-17/the-julge/users/0fa50956-0618-44bf-a287-218bcebfe4ff/alerts
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwZmE1MDk1Ni0wNjE4LTQ0YmYtYTI4Ny0yMThiY2ViZmU0ZmYiLCJpYXQiOjE3MTQxOTEzNzR9.GDbIfP9ZDuw_ZiiGpvaFRr58Cr6VY9x2sL4TrUPQEuk

###
POST https://bootcamp-api.codeit.kr/api/4-17/the-julge/shops/0ecbcfcb-1c78-4f2b-93cd-ff6267a2099a/notices/06157300-6580-4d73-b1be-69df0bcda2f4/applications
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NGZjZjM3Ni02MTFlLTRhYmUtYTExZS03ZTVhYWRmNWE2ZDQiLCJpYXQiOjE3MTQxMzYzNjN9.Z-fIpdFaiJcCHDXmWEe2aIAZC8-KbAeoCxF5SnQkdN4

###
GET https://bootcamp-api.codeit.kr/api/4-17/the-julge/notices?address=서울시%20종로구&sort=pay
Content-Type: application/json