POST https://bootcamp-api.codeit.kr/api/4-17/the-julge/shops
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYmU0ZjNlNi04ZDM1LTQwM2MtOGZiZC0yODQyZTI1YmRlNjEiLCJpYXQiOjE3MTQxMzc2MTN9.fMXQ2hDcUdG9beWHQLeOaNK1cq6tRle-4x_8BFsCbjM

{
  "name": "서울왕갈비통닭",
    "category": "양식",
    "address1": "서울시 종로구",
    "address2": "안알랴줌",
    "description": "이집맛없어이집맛없어이집맛없어이집맛없어이집맛없어이집맛없어이집맛없어이집맛없어이집맛없어이집맛없어이집맛없어이집맛없어",
    "imageUrl": "https://bootcamp-project-api.s3.ap-northeast-2.amazonaws.com/4-17/the-julge/d4c507f1-21e7-4e15-9d89-b8b656025a9b-sprint%20배너.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=AKIAQ32VNU3YNU4IZOFJ%2F20240426%2Fap-northeast-2%2Fs3%2Faws4_request&X-Amz-Date=20240426T132027Z&X-Amz-Expires=300&X-Amz-Signature=a73aac42c92a5d5839b90b3771d4e859b75b91cf481b8dfbe804ecf3825d5bb0&X-Amz-SignedHeaders=host&x-amz-acl=public-read&x-id=PutObject",
    "originalHourlyPay": "11000"
}

###
GET  https://bootcamp-api.codeit.kr/api/4-17/the-julge/users/ebe4f3e6-8d35-403c-8fbd-2842e25bde61

###
POST https://bootcamp-api.codeit.kr/api/4-17/the-julge/shops/08069f22-3781-402e-810c-4bf06030baf6/notices
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYmU0ZjNlNi04ZDM1LTQwM2MtOGZiZC0yODQyZTI1YmRlNjEiLCJpYXQiOjE3MTQxMzc2MTN9.fMXQ2hDcUdG9beWHQLeOaNK1cq6tRle-4x_8BFsCbjM

{
    "hourlyPay": "12000",
    "startsAt": "2024-11-23T00:00:00Z",
    "workhour": "10",
    "description": "일해라"
}

###
GET https://bootcamp-project-api.s3.ap-northeast-2.amazonaws.com/4-17/the-julge/030f50c2-ad84-4db4-ba22-6697dad61cfe-sprint%20배너.png


###
GET https://bootcamp-api.codeit.kr/api/4-17/the-julge/users/84fcf376-611e-4abe-a11e-7e5aadf5a6d4/alerts
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI4NGZjZjM3Ni02MTFlLTRhYmUtYTExZS03ZTVhYWRmNWE2ZDQiLCJpYXQiOjE3MTQxMzYzNjN9.Z-fIpdFaiJcCHDXmWEe2aIAZC8-KbAeoCxF5SnQkdN4