export const CANCEL_TOAST = '취소했어요';
export const COMPLETE_TOAST = '신청완료!';
export const LOCATION_FILTER = [
  { id: 1, name: '서울시 종로구' },
  { id: 2, name: '서울시 중구' },
  { id: 3, name: '서울시 용산구' },
  { id: 4, name: '서울시 성동구' },
  { id: 5, name: '서울시 광진구' },
  { id: 6, name: '서울시 동대문구' },
  { id: 7, name: '서울시 중랑구' },
  { id: 8, name: '서울시 성북구' },
  { id: 9, name: '서울시 강북구' },
  { id: 10, name: '서울시 도봉구' },
  { id: 11, name: '서울시 노원구' },
  { id: 12, name: '서울시 은평구' },
  { id: 13, name: '서울시 서대문구' },
  { id: 14, name: '서울시 마포구' },
  { id: 15, name: '서울시 양천구' },
  { id: 16, name: '서울시 강서구' },
  { id: 17, name: '서울시 구로구' },
  { id: 18, name: '서울시 금천구' },
  { id: 19, name: '서울시 영등포구' },
  { id: 20, name: '서울시 동작구' },
  { id: 21, name: '서울시 관악구' },
  { id: 22, name: '서울시 서초구' },
  { id: 23, name: '서울시 강남구' },
  { id: 24, name: '서울시 송파구' },
  { id: 25, name: '서울시 강동구' },
];
